networks:
  project-3-network:
    driver: bridge

x-kafka-common: &kafka-common
  image: bitnami/kafka:latest
  networks:
    - project-3-network

x-kafka-common-env: &kafka-common-env
  KAFKA_ENABLE_KRAFT: yes
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1000@kafka-controller-0:9091,1001@kafka-controller-1:9092,1002@kafka-controller-2:9093
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  ALLOW_PLAINTEXT_LISTENER: yes
  KAFKA_KRAFT_CLUSTER_ID: PROJECT_3_KAFKA_CLUSTER

services:
  kafka-controller-0:
    <<: *kafka-common
    container_name: kafka-controller-0
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_NODE_ID: 1000
      KAFKA_CFG_PROCESS_ROLES: controller
      KAFKA_CFG_LISTENERS: CONTROLLER://:9091

  kafka-controller-1:
    <<: *kafka-common
    container_name: kafka-controller-1
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_NODE_ID: 1001
      KAFKA_CFG_PROCESS_ROLES: controller
      KAFKA_CFG_LISTENERS: CONTROLLER://:9092

  kafka-controller-2:
    <<: *kafka-common
    container_name: kafka-controller-2
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_NODE_ID: 1002
      KAFKA_CFG_PROCESS_ROLES: controller
      KAFKA_CFG_LISTENERS: CONTROLLER://:9093

  kafka-broker-0:
    <<: *kafka-common
    container_name: kafka-broker-0
    ports:
      - "9094:9094"
    depends_on:
      - kafka-controller-0
      - kafka-controller-1
      - kafka-controller-2
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CLIENT_LISTENER_NAME: EXTERNAL
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://kafka-broker-0:9094

  kafka-broker-1:
    <<: *kafka-common
    container_name: kafka-broker-1
    ports:
      - "9095:9095"
    depends_on:
      - kafka-controller-0
      - kafka-controller-1
      - kafka-controller-2
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CLIENT_LISTENER_NAME: EXTERNAL
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://kafka-broker-1:9095

  kafka-broker-2:
    <<: *kafka-common
    container_name: kafka-broker-2
    ports:
      - "9096:9096"
    depends_on:
      - kafka-controller-0
      - kafka-controller-1
      - kafka-controller-2
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CLIENT_LISTENER_NAME: EXTERNAL
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9096
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://kafka-broker-2:9096

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - project-3-network
    ports:
      - "8080:8080"
    depends_on:
      kafka-broker-0:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: project-3-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-0:9092,kafka-broker-1:9092,kafka-broker-2:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    hostname: schema-registry
    networks:
      - project-3-network
    ports:
      - "8081:8081"
    depends_on:
      kafka-broker-0:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/subjects" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-2:9092,PLAINTEXT://kafka-broker-1:9092,PLAINTEXT://kafka-broker-0:9092
      SCHEMA_REGISTRY_DEBUG: true

  postgres:
    image: debezium/postgres:16
    hostname: postgres
    container_name: postgres
    networks:
      - project-3-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres-user", "-d", "project3" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: project3

  kafka-connect:
    build:
      context: ./kafka-connect
    container_name: kafka-connect
    networks:
      - project-3-network
    ports:
      - "8083:8083"
      - "9875:9875"
      - "9876:9876"
    depends_on:
      kafka-broker-0:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    volumes:
      - ./plugins/:/etc/kafka-connect/jars
    command: >
      bash -c "
        /etc/confluent/docker/run &
        sleep 20 &&
        curl -X PUT -H 'Content-Type: application/json' \
          --data @/kafka/connectors/debezium-postgres-config.json \
          http://localhost:8083/connectors/pg-connector/config
        wait -n
      "
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-broker-0:9092,kafka-broker-1:9092,kafka-broker-2:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_CONFIG_STORAGE_TOPIC: connect-config-storage
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offset-storage
      CONNECT_STATUS_STORAGE_TOPIC: connect-status-storage
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081/
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081/
      KAFKA_JMX_PORT: 9875
      KAFKA_OPTS: -javaagent:/opt/jmx_prometheus_javaagent-0.15.0.jar=9876:/opt/kafka-connect.yml
      CONNECT_CONFIG_PROVIDERS: file
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars

  prometheus:
    image: prom/prometheus:v2.30.3
    networks:
      - project-3-network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    networks:
      - project-3-network
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    networks:
      - project-3-network
    depends_on:
      - kafka-connect
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker-2:9096,kafka-broker-1:9095,kafka-broker-0:9094
      SCHEMA_REGISTRY_URL: http://schema-registry:8081