global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kafka-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - kafka-exporter:9308

  - job_name: jmx-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - kafka-controller-0:9404
          - kafka-controller-1:9404
          - kafka-controller-2:9404
          - kafka-broker-0:9404
          - kafka-broker-1:9404
          - kafka-broker-2:9404