spring:
  application:
    name: consumer
  kafka:
    bootstrap-servers: kafka-broker-0:9092,kafka-broker-1:9092,kafka-broker-2:9092
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: practical_work_5-group
      enable-auto-commit: false
      auto-offset-reset: latest
      max-poll-records: 500
      max-poll-interval: 300000
      heartbeat-interval: 3000
      properties:
        schema.registry.url: http://schema-registry:8081
        specific.avro.reader: false
    listener:
      concurrency: 3
      type: batch
      ack-mode: BATCH
      poll-timeout: 1500